[package]
name = "spotlight_save"
version = "0.1.0"
authors = ["Steven Lee <leexgone@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "3.1"
home = "0.5"
image = "0.24"
chrono = "0.4"